### PR TITLE
🎁 Add graceful fallback of preprocessing

### LINKED ISSUE #282: Graceful handling of derivative rodeo preprocessed file missing
Referencing the below code:

-   The \`input\_uri\` is a local \`<file://>\`; if it exists we use it (note it likely does not exist yet).
-   The \`output\_location\_template\` specifies the output format of the page images.
-   The \`preprocessed\_location\_template\` is the location of the PDF in “SpaceStone” (e.g. S3)

In the case where SpaceStone failed to fetch the original PDF, we would have a case where the file pointed to by the \`preprocessed\_location\_template\` does not exist.  At the time of processing, we do have the \`file\_set\` and it should include the URL to the original PDF.  Thus we might want to introduce a graceful fallback value for \`preprocessed\_location\_template\`.

```ruby
def split_files
  DerivativeRodeo::Generators::PdfSplitGenerator.new(
    input_uris: [@input_uri],
    output_location_template: output_location_template,
    preprocessed_location_template: preprocessed_location_template
  ).generated_files.map(&:file_path)
rescue => e
  message = "#{self.class}##{__method__} encountered `#{e.class}' “#{e}” for " \
            "input_uri: #{@input_uri.inspect}, " \
            "output_location_template: #{output_location_template.inspect}, and" \
            "preprocessed_location_template: #{preprocessed_location_template.inspect}."
  exception = RuntimeError.new(message)
  exception.set_backtrace(e.backtrace)
  raise exception
end
```

<https://github.com/scientist-softserv/iiif_print/blob/a86c2e570c9019da2280003cd88e106147e21f69/lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb#L68-L82>

If the template were the following:

```ruby
location = DerivativeRodeo::StorageLocations::BaseLocation.from_uri(preprocessed_location_template)

return preprocessed_location_template if location.exist?

file_set.remote_url # Assuming that works; which is something to test
```

### PR DESCRIPTION
**Pull request by jeremyf**
Prior to this commit, if we did not actually have preprocessed file in
the remote system, we'd encounter errors with files missing; we assumed
we could "copy" the preprocessed url to the local file.

With this commit, we check to see if the preprocessed file exists.  Then
fallback to a specified FileSet#remote_url and the fallback even
further.

The specs define the expected behavior.

Closes #282

Related to:

- https://github.com/scientist-softserv/iiif_print/issues/282

### CODE REVIEW

File: lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb [hunk 1]
```diff
@@ -61,19 +68,63 @@ def initialize(filename, file_set:, output_tmp_dir: Dir.tmpdir)
...
+      # rubocop:disable Metrics/AbcSize
+      # rubocop:disable Metrics/MethodLength
+      def preprocessed_location_template
+        return @preprocessed_location_template if defined?(@preprocessed_location_template)
+
+        derivative_rodeo_candidate = IiifPrint::DerivativeRodeoService.derivative_rodeo_uri(file_set: file_set, filename: filename)
+
+        @preprocessed_location_template =
+          if rodeo_conformant_uri_exists?(derivative_rodeo_candidate)
+            Rails.logger.debug("#{self.class}##{__method__} found existing file at location #{derivative_rodeo_candidate}.  High five partner!")
```
Comment (kirkkwang) [inline lib/iiif_print/split_pdfs/derivative_rodeo_splitter.rb:80]: Hah!

**Review by kirkkwang — APPROVED** [review]
